#!/bin/bash
# 
# 函数: setTime
# 作用: 简单定时器，定时执行任务，基于 sleep ，易受影响。
# 参数: 
#      $1: 要显示的提示语
# 返回值:
#      永远为 0
# 

_setTime_readme_(){
    echo -e "\t简单定时器，定时执行任务，基于 sleep ，易受影响。详细内容 调用 setTime / 调用时添加 -h 参数"
}

_setTime_help_(){
    echo
    echo -e "  setTime:"
    echo
    echo -e "\t-t:\t\t间隔时间"
    echo -e "\t-s:\t\t执行的内容"
    echo -e "\t-h:\t\t打印帮助信息"
    echo
    echo -e "  例子："
    echo -e '\tsetTime 1 "echo hello"\t间隔1秒执行一次echo hello'
    echo
}

#setTime
    if [ $# = 0 -o "$1" = "-h" ];then
        _setTime_help_
    else
        while [ true ];do
            sleep $1
            $2
        done
    fi
    exit 0
