#!/bin/bash
# 
# 函数: user
# 作用: 提供root权限执行命令（需要环境中有password变量，如果没有就提示添加）
# 参数: 
#      $*: 需要root权限执行的命令
# 返回值:
#      0
# 

PATH=/usr/bin:/bin:./../../function:./function:./

if [ ! "$Whi" ];then
    Who=$(whoami)
fi

if [ "$*" ];then
    sudo -u $Who $*
    exit 0
fi

exit 1