#!/bin/bash

if [ ! "$1" ];then
    text="默认提示：请输入相关内容"
else
    text=$1
fi

if [ ! "$2" ];then
    tips=""
else
    tips=$2
fi

content=$(whiptail --inputbox $text 10 60 $tips 3>&1 1>&2 2>&3)

if [ ! "$content" ];then
    exit 1
fi

echo $content
exit 0